import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CustomProvider from "@/components/CustomProvider";

export const metadata: Metadata = {
  title: "Ecommerce Website",
  description: "Generated by create next app",
};

export default function Layout({children}:{children:React.ReactNode}){
  return(
    <html>
      <body>
        <CustomProvider>
          <div className="bg-white flex flex-col min-h-screen">
            <Navbar />
            <div className="flex-1">
            {children}
            </div>
            <Footer />
          </div>
        </CustomProvider>
      </body>
    </html>  
  );
}